name: Build and Push to Google Container Registry
# create simple trigger based on everytime we create new tag in this repository
on:
  push:
    tags:
      - "*"

jobs:
  BuildPush:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GCR
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          
      - name: Build Docker Image
        run: |-
          cd ${{ github.workspace }}
          task image-build
        
      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet
        
      - name: Push Docker Image to Google Container Registry
        run: |-
          task image-tag
          task image-push
